--- 
- name: install postgres
  #yum: 
  #  name: postgresql-server
  #  state: latest
  command: "yum install -y postgresql-server"

- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: initilize postgres
  command: postgresql-setup initdb
  args: 
    creates: /var/lib/pgsql/data/base

- name: initilize postgres some more
  command: chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started

